import type { Template, CanvasComponent } from '../types';
import { generateId } from './helpers';

const makeId = () => generateId();

const ecommerceBannerComponents: CanvasComponent[] = [
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 0,
    width: 1080,
    height: 400,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '顶部背景',
    zIndex: 1,
    fill: 'linear-gradient(135deg, #1A237E 0%, #3949AB 100%)',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: 850,
    y: 60,
    width: 280,
    height: 280,
    rotation: 0,
    opacity: 0.3,
    visible: true,
    locked: false,
    name: '装饰圆形1',
    zIndex: 2,
    fill: '#FF6F00',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: -50,
    y: 100,
    width: 180,
    height: 180,
    rotation: 0,
    opacity: 0.2,
    visible: true,
    locked: false,
    name: '装饰圆形2',
    zIndex: 2,
    fill: '#FFB74D',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 100,
    width: 700,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '主标题',
    zIndex: 3,
    content: '618 年中大促',
    fontSize: 72,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'left',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 200,
    width: 600,
    height: 60,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '副标题',
    zIndex: 3,
    content: '全场低至3折 · 限时抢购',
    fontSize: 36,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'left',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 80,
    y: 280,
    width: 200,
    height: 60,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: 'CTA按钮',
    zIndex: 3,
    fill: '#FF6F00',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 30,
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 290,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '按钮文字',
    zIndex: 4,
    content: '立即抢购 →',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 400,
    width: 1080,
    height: 620,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '底部背景',
    zIndex: 1,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
];

const promotionPosterComponents: CanvasComponent[] = [
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 0,
    width: 1080,
    height: 1920,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '背景',
    zIndex: 1,
    fill: 'linear-gradient(180deg, #1A237E 0%, #283593 40%, #FF6F00 100%)',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: 700,
    y: -100,
    width: 500,
    height: 500,
    rotation: 0,
    opacity: 0.15,
    visible: true,
    locked: false,
    name: '装饰大圆',
    zIndex: 2,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'text',
    x: 0,
    y: 200,
    width: 1080,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '限时特惠',
    zIndex: 3,
    content: '限时特惠',
    fontSize: 64,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 0,
    y: 350,
    width: 1080,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '主标题',
    zIndex: 3,
    content: '狂欢盛典',
    fontSize: 140,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'italic',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 290,
    y: 700,
    width: 500,
    height: 200,
    rotation: 0,
    opacity: 0.95,
    visible: true,
    locked: false,
    name: '价格框',
    zIndex: 3,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 20,
  },
  {
    id: makeId(),
    type: 'text',
    x: 290,
    y: 720,
    width: 500,
    height: 60,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '原价',
    zIndex: 4,
    content: '原价 ¥599',
    fontSize: 28,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'underline',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#999999',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 290,
    y: 780,
    width: 500,
    height: 120,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '特价',
    zIndex: 4,
    content: '¥199',
    fontSize: 96,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FF6F00',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 0,
    y: 1000,
    width: 1080,
    height: 60,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '活动说明',
    zIndex: 3,
    content: '全店满300减50 · 满500减100',
    fontSize: 32,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
];

const couponComponents: CanvasComponent[] = [
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 0,
    width: 1080,
    height: 1920,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '背景',
    zIndex: 1,
    fill: '#FFF3E0',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'rect',
    x: 90,
    y: 400,
    width: 900,
    height: 450,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '优惠券主体',
    zIndex: 2,
    fill: '#FF6F00',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 24,
  },
  {
    id: makeId(),
    type: 'circle',
    x: 60,
    y: 600,
    width: 80,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '左缺口',
    zIndex: 3,
    fill: '#FFF3E0',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: 940,
    y: 600,
    width: 80,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '右缺口',
    zIndex: 3,
    fill: '#FFF3E0',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'text',
    x: 90,
    y: 440,
    width: 900,
    height: 60,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '优惠券标题',
    zIndex: 4,
    content: '专享优惠券',
    fontSize: 36,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 90,
    y: 520,
    width: 400,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '金额',
    zIndex: 4,
    content: '¥100',
    fontSize: 140,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 490,
    y: 520,
    width: 2,
    height: 220,
    rotation: 0,
    opacity: 0.3,
    visible: true,
    locked: false,
    name: '分隔线',
    zIndex: 4,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'text',
    x: 520,
    y: 560,
    width: 440,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '使用条件',
    zIndex: 4,
    content: '满500元\n即可使用',
    fontSize: 36,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'left',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 90,
    y: 900,
    width: 900,
    height: 50,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '有效期',
    zIndex: 4,
    content: '有效期至 2026.12.31',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#666666',
    backgroundColor: 'transparent',
  },
];

const countdownComponents: CanvasComponent[] = [
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 0,
    width: 1080,
    height: 1920,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '背景',
    zIndex: 1,
    fill: 'linear-gradient(135deg, #0D1333 0%, #1A237E 50%, #0D1333 100%)',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'text',
    x: 0,
    y: 200,
    width: 1080,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '提示语',
    zIndex: 2,
    content: '距离活动开始还有',
    fontSize: 40,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#B39DDB',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 0,
    y: 320,
    width: 1080,
    height: 120,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '大标题',
    zIndex: 2,
    content: '双11 狂欢夜',
    fontSize: 88,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'italic',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 100,
    y: 600,
    width: 200,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '天卡片',
    zIndex: 2,
    fill: 'rgba(255, 111, 0, 0.15)',
    stroke: '#FF6F00',
    strokeWidth: 2,
    borderRadius: 16,
  },
  {
    id: makeId(),
    type: 'text',
    x: 100,
    y: 640,
    width: 200,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '天数',
    zIndex: 3,
    content: '03',
    fontSize: 88,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FF6F00',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 100,
    y: 740,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '天标签',
    zIndex: 3,
    content: 'DAYS',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 340,
    y: 600,
    width: 200,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '时卡片',
    zIndex: 2,
    fill: 'rgba(255, 111, 0, 0.15)',
    stroke: '#FF6F00',
    strokeWidth: 2,
    borderRadius: 16,
  },
  {
    id: makeId(),
    type: 'text',
    x: 340,
    y: 640,
    width: 200,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '小时数',
    zIndex: 3,
    content: '12',
    fontSize: 88,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FF6F00',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 340,
    y: 740,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '时标签',
    zIndex: 3,
    content: 'HOURS',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 580,
    y: 600,
    width: 200,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '分卡片',
    zIndex: 2,
    fill: 'rgba(255, 111, 0, 0.15)',
    stroke: '#FF6F00',
    strokeWidth: 2,
    borderRadius: 16,
  },
  {
    id: makeId(),
    type: 'text',
    x: 580,
    y: 640,
    width: 200,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '分钟数',
    zIndex: 3,
    content: '45',
    fontSize: 88,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FF6F00',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 580,
    y: 740,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '分标签',
    zIndex: 3,
    content: 'MINUTES',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 820,
    y: 600,
    width: 200,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '秒卡片',
    zIndex: 2,
    fill: 'rgba(255, 111, 0, 0.15)',
    stroke: '#FF6F00',
    strokeWidth: 2,
    borderRadius: 16,
  },
  {
    id: makeId(),
    type: 'text',
    x: 820,
    y: 640,
    width: 200,
    height: 100,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '秒数',
    zIndex: 3,
    content: '30',
    fontSize: 88,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1,
    textAlign: 'center',
    color: '#FF6F00',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 820,
    y: 740,
    width: 200,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '秒标签',
    zIndex: 3,
    content: 'SECONDS',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFCC80',
    backgroundColor: 'transparent',
  },
];

const socialCoverComponents: CanvasComponent[] = [
  {
    id: makeId(),
    type: 'rect',
    x: 0,
    y: 0,
    width: 1080,
    height: 1080,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '背景',
    zIndex: 1,
    fill: 'linear-gradient(45deg, #1A237E 0%, #5C6BC0 100%)',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: 800,
    y: -150,
    width: 500,
    height: 500,
    rotation: 0,
    opacity: 0.2,
    visible: true,
    locked: false,
    name: '装饰圆1',
    zIndex: 2,
    fill: '#FF6F00',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'circle',
    x: -200,
    y: 700,
    width: 600,
    height: 600,
    rotation: 0,
    opacity: 0.15,
    visible: true,
    locked: false,
    name: '装饰圆2',
    zIndex: 2,
    fill: '#FFB74D',
    stroke: 'transparent',
    strokeWidth: 0,
  },
  {
    id: makeId(),
    type: 'rect',
    x: 80,
    y: 80,
    width: 120,
    height: 120,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '头像框',
    zIndex: 3,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 60,
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 100,
    width: 120,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '头像文字',
    zIndex: 4,
    content: 'LOGO',
    fontSize: 28,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'center',
    color: '#1A237E',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 240,
    y: 100,
    width: 600,
    height: 50,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '品牌名',
    zIndex: 3,
    content: '精品电商',
    fontSize: 40,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'left',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 240,
    y: 150,
    width: 600,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '账号',
    zIndex: 3,
    content: '@premium_shop',
    fontSize: 24,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'left',
    color: '#B39DDB',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 400,
    width: 920,
    height: 200,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '标语',
    zIndex: 3,
    content: '品质生活\n从这里开始',
    fontSize: 80,
    fontFamily: 'Playfair Display',
    fontWeight: 'bold',
    fontStyle: 'italic',
    textDecoration: 'none',
    lineHeight: 1.2,
    textAlign: 'left',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 750,
    width: 920,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '简介',
    zIndex: 3,
    content: '精选全球好物 · 品质保障 · 极速发货',
    fontSize: 28,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'left',
    color: '#E0E0E0',
    backgroundColor: 'transparent',
  },
  {
    id: makeId(),
    type: 'rect',
    x: 80,
    y: 900,
    width: 280,
    height: 80,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '关注按钮',
    zIndex: 3,
    fill: '#FF6F00',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 40,
  },
  {
    id: makeId(),
    type: 'text',
    x: 80,
    y: 920,
    width: 280,
    height: 40,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    name: '按钮文字',
    zIndex: 4,
    content: '+ 关注我们',
    fontSize: 28,
    fontFamily: 'Noto Sans SC',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    lineHeight: 1.5,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
];

export const BUILTIN_TEMPLATES: Template[] = [
  {
    id: 'tpl-banner',
    name: '电商Banner',
    canvasWidth: 1080,
    canvasHeight: 1020,
    components: ecommerceBannerComponents,
  },
  {
    id: 'tpl-poster',
    name: '活动海报',
    canvasWidth: 1080,
    canvasHeight: 1920,
    components: promotionPosterComponents,
  },
  {
    id: 'tpl-coupon',
    name: '优惠券',
    canvasWidth: 1080,
    canvasHeight: 1920,
    components: couponComponents,
  },
  {
    id: 'tpl-countdown',
    name: '倒计时页',
    canvasWidth: 1080,
    canvasHeight: 1920,
    components: countdownComponents,
  },
  {
    id: 'tpl-social',
    name: '社交媒体封面',
    canvasWidth: 1080,
    canvasHeight: 1080,
    components: socialCoverComponents,
  },
];

export const getDefaultTemplate = (): Template => {
  return JSON.parse(JSON.stringify(BUILTIN_TEMPLATES[0]));
};
