export const COLORS = {
  BACKGROUND: '#000000',
  TRUNK_START: '#4e342e',
  TRUNK_END: '#66bb6a',
  ANIMAL: '#e53935',
  PLANT: '#43a047',
  MICROBE: '#1e88e5',
  HIGHLIGHT: '#ffd700',
  STREAM_BASE: '#ffffff40',
  PULSE: '#ffffff',
  UI_PANEL_BG: '#0a0a1e88',
  UI_PANEL_BORDER: '#ffffff15',
  UI_TEXT: '#ffffff',
  UI_TEXT_SECONDARY: '#b0b0b0',
  UI_PLACEHOLDER: '#888888',
  UI_BUTTON_BG: '#ffffff10',
  UI_CLOSE_BTN: '#ffffff80',
} as const;

export const SIZES = {
  NODE_RADIUS_MIN: 0.3,
  NODE_RADIUS_MAX: 1.2,
  NODE_RADIUS_EXPANDED: 1.5,
  PARTICLE_SIZE_MIN: 0.02,
  PARTICLE_SIZE_MAX: 0.06,
  PARTICLE_PER_NODE_MIN: 20,
  PARTICLE_PER_NODE_MAX: 50,
  STREAM_PARTICLE_SIZE_MIN: 0.006,
  STREAM_PARTICLE_SIZE_MAX: 0.012,
  STREAM_PARTICLE_COUNT_MIN: 30,
  STREAM_PARTICLE_COUNT_MAX: 50,
  TREE_RADIUS_MIN: 8,
  TREE_RADIUS_MAX: 12,
  GROUND_STAR_SIZE: 0.01,
  GROUND_GRID_SIZE: 10,
  UI_PANEL_WIDTH: 320,
  UI_PANEL_RADIUS: 16,
  UI_PANEL_PADDING: 20,
  UI_CLOSE_BTN_SIZE: 24,
  UI_SEARCH_HEIGHT: 40,
  UI_TAG_RADIUS: 8,
  UI_TAG_PADDING_X: 10,
  UI_TAG_PADDING_Y: 4,
  UI_CAPSULE_HEIGHT: 32,
  UI_CAPSULE_RADIUS: 16,
} as const;

export const ANIMATION = {
  FLOAT_AMPLITUDE: 0.05,
  FLOAT_PERIOD_MIN: 1000,
  FLOAT_PERIOD_MAX: 2000,
  ROTATION_DAMPING: 0.92,
  ROTATION_SPEED: 0.5,
  ZOOM_MIN: 0.5,
  ZOOM_MAX: 3,
  ZOOM_SPEED: 0.8,
  STREAM_FLOW_SPEED: 0.5,
  STREAM_FLOW_SPEED_BOOSTED: 1.0,
  CLICK_EXPAND_DURATION: 800,
  CLICK_STREAM_BOOST_DURATION: 1500,
  PULSE_SPEED: 2,
  PULSE_MAX_RADIUS: 8,
  PULSE_WIDTH: 0.05,
  SEARCH_DEBOUNCE: 300,
  SEARCH_FLASH_PERIOD: 500,
  GROUND_STAR_OPACITY: 0.3,
  GROUND_STAR_COUNT: 100,
} as const;

export const SPECIES_DATA = [
  { name: '人类', category: 'animal' as const, description: '智人，具有高度智慧和复杂社会结构的灵长类动物。', relatedSpecies: ['黑猩猩', '大猩猩'] },
  { name: '黑猩猩', category: 'animal' as const, description: '与人类亲缘关系最近的物种，具有使用工具的能力。', relatedSpecies: ['人类', '大猩猩'] },
  { name: '大猩猩', category: 'animal' as const, description: '现存最大的灵长类动物，生活在非洲热带雨林中。', relatedSpecies: ['人类', '黑猩猩'] },
  { name: '狮子', category: 'animal' as const, description: '草原之王，群居的大型猫科动物。', relatedSpecies: ['老虎', '猎豹'] },
  { name: '老虎', category: 'animal' as const, description: '最大的猫科动物，独居，具有独特的条纹图案。', relatedSpecies: ['狮子', '猎豹'] },
  { name: '猎豹', category: 'animal' as const, description: '陆地奔跑速度最快的动物，时速可达120公里。', relatedSpecies: ['狮子', '老虎'] },
  { name: '大象', category: 'animal' as const, description: '陆地上最大的哺乳动物，具有长鼻子和大耳朵。', relatedSpecies: ['犀牛', '河马'] },
  { name: '犀牛', category: 'animal' as const, description: '厚皮动物，鼻子上长有一只或两只角。', relatedSpecies: ['大象', '河马'] },
  { name: '河马', category: 'animal' as const, description: '半水生哺乳动物，嘴巴巨大，牙齿锋利。', relatedSpecies: ['大象', '犀牛'] },
  { name: '蓝鲸', category: 'animal' as const, description: '地球上最大的动物，生活在海洋中，以浮游生物为食。', relatedSpecies: ['虎鲸', '海豚'] },
  { name: '虎鲸', category: 'animal' as const, description: '海洋顶级捕食者，具有高度的智慧和复杂的社会结构。', relatedSpecies: ['蓝鲸', '海豚'] },
  { name: '海豚', category: 'animal' as const, description: '聪明的海洋哺乳动物，以其友好和智慧著称。', relatedSpecies: ['蓝鲸', '虎鲸'] },
  { name: '老鹰', category: 'animal' as const, description: '猛禽之王，视力极佳，可在高空发现猎物。', relatedSpecies: ['猫头鹰', '猎隼'] },
  { name: '猫头鹰', category: 'animal' as const, description: '夜行性猛禽，头部可旋转270度。', relatedSpecies: ['老鹰', '猎隼'] },
  { name: '猎隼', category: 'animal' as const, description: '最快的鸟类，俯冲速度可达380公里/小时。', relatedSpecies: ['老鹰', '猫头鹰'] },
  { name: '橡树', category: 'plant' as const, description: '长寿的落叶乔木，木材坚硬，果实为橡子。', relatedSpecies: ['枫树', '松树'] },
  { name: '枫树', category: 'plant' as const, description: '秋季叶子变红变黄，汁液可制作糖浆。', relatedSpecies: ['橡树', '松树'] },
  { name: '松树', category: 'plant' as const, description: '常绿针叶树，木材广泛用于建筑。', relatedSpecies: ['橡树', '枫树'] },
  { name: '玫瑰', category: 'plant' as const, description: '花中皇后，象征爱情，茎上有刺。', relatedSpecies: ['牡丹', '菊花'] },
  { name: '牡丹', category: 'plant' as const, description: '花中之王，花朵硕大艳丽。', relatedSpecies: ['玫瑰', '菊花'] },
  { name: '菊花', category: 'plant' as const, description: '秋季开花，品种繁多，具有药用价值。', relatedSpecies: ['玫瑰', '牡丹'] },
  { name: '水稻', category: 'plant' as const, description: '世界最重要的粮食作物之一，养活数十亿人。', relatedSpecies: ['小麦', '玉米'] },
  { name: '小麦', category: 'plant' as const, description: '全球广泛种植的谷物，制作面包的主要原料。', relatedSpecies: ['水稻', '玉米'] },
  { name: '玉米', category: 'plant' as const, description: '高产作物，用途广泛，从食物到燃料。', relatedSpecies: ['水稻', '小麦'] },
  { name: '仙人掌', category: 'plant' as const, description: '沙漠植物，茎肉质储存水分，叶子退化为刺。', relatedSpecies: ['多肉', '芦荟'] },
  { name: '多肉', category: 'plant' as const, description: '肉质植物，耐旱，种类繁多，形态各异。', relatedSpecies: ['仙人掌', '芦荟'] },
  { name: '芦荟', category: 'plant' as const, description: '药用植物，汁液可治疗烧伤和皮肤问题。', relatedSpecies: ['仙人掌', '多肉'] },
  { name: '大肠杆菌', category: 'microbe' as const, description: '肠道中常见的细菌，大部分菌株无害。', relatedSpecies: ['乳酸菌', '酵母菌'] },
  { name: '乳酸菌', category: 'microbe' as const, description: '发酵乳制品的有益细菌，维护肠道健康。', relatedSpecies: ['大肠杆菌', '酵母菌'] },
  { name: '酵母菌', category: 'microbe' as const, description: '单细胞真菌，用于面包发酵和酿酒。', relatedSpecies: ['大肠杆菌', '乳酸菌'] },
  { name: '青霉素', category: 'microbe' as const, description: '第一种抗生素，由青霉菌产生，拯救无数生命。', relatedSpecies: ['链霉素', '四环素'] },
  { name: '链霉素', category: 'microbe' as const, description: '氨基糖苷类抗生素，治疗结核病等。', relatedSpecies: ['青霉素', '四环素'] },
  { name: '四环素', category: 'microbe' as const, description: '广谱抗生素，治疗多种细菌感染。', relatedSpecies: ['青霉素', '链霉素'] },
  { name: '新冠病毒', category: 'microbe' as const, description: '冠状病毒的一种，引起COVID-19大流行。', relatedSpecies: ['流感病毒', '艾滋病毒'] },
  { name: '流感病毒', category: 'microbe' as const, description: '引起流行性感冒，每年季节性流行。', relatedSpecies: ['新冠病毒', '艾滋病毒'] },
  { name: '艾滋病毒', category: 'microbe' as const, description: '引起获得性免疫缺陷综合征，攻击免疫系统。', relatedSpecies: ['新冠病毒', '流感病毒'] },
  { name: '阿米巴原虫', category: 'microbe' as const, description: '单细胞原生动物，可引起阿米巴痢疾。', relatedSpecies: ['疟原虫', '草履虫'] },
  { name: '疟原虫', category: 'microbe' as const, description: '通过蚊子传播，引起疟疾。', relatedSpecies: ['阿米巴原虫', '草履虫'] },
  { name: '草履虫', category: 'microbe' as const, description: '常见的原生动物，形状像鞋底，有纤毛。', relatedSpecies: ['阿米巴原虫', '疟原虫'] },
  { name: '硅藻', category: 'microbe' as const, description: '具有硅质外壳的藻类，是海洋食物链的基础。', relatedSpecies: ['蓝藻', '绿藻'] },
  { name: '蓝藻', category: 'microbe' as const, description: '能进行光合作用的细菌，产生地球大部分氧气。', relatedSpecies: ['硅藻', '绿藻'] },
  { name: '绿藻', category: 'microbe' as const, description: '绿色藻类，被认为是陆地植物的祖先。', relatedSpecies: ['硅藻', '蓝藻'] },
] as const;
